BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB gettext(u'Signup') BBBBBBBB

BBBBB BBBBBBB
BBBB BBBBBBB BBBBBBBBBBBBB
BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXX XXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXX
				XXXX gettext(u'Quase lá!') XXXXX
				XXXX gettext(u'Coloque seu nome de usuário e seu email para concluir o cadastro!') XXXXX
				XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Voltar ao início') XXXX
		XXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXXX
		XXXXX
		XXXX XXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX
        BBBBBBBBBB
				
        BB BBBBBBBBBBBBBBBBBBBB
				XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX
        BBBBB
        XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Sign Up')  XXXXXXXXXXXXXXXX				
			XXXXXXX
			XXXX
		XXXXXX
		
		XXXXXX
	XXXXXX
XXXXXXXXXX
BBBBBBBB
