BBBB BBBB
BBBB BBBBBB

XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXX
        XXXXXXXX XXXX X XXXXXX X
            XXXXXXXXXXX XX
        X
        XXXXXXXX
            XXXXXXXXXXX XX
        X
        XXXXXXXX XXXX X XXXXXXXXXXXX X
            XXXXXXXXXXX XXXX XXXXXXXXXXXX
        X
        XXXXXXXXXXXXXX
            XXXXXXXXXXX XXXX XXXXXXXXXXXX
        X
    XXXXXXXX
XXXXXXX

XXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB


    BBBBB BBBB
    XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB BBBBBBB
        
        BBBBBBBB     
        BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX gettext(u'Erros:') XXXXXXXXXXXXX
        XXXX
            BBB BBBBBB BBBBBB BB BBBBBBBBBBBBBBBBB
            BBB BBBBB BB BBBBBB
                XXXXXXXXX
            BBBBBB
            BBBBBB
        XXXXX
        XXXXXX
    BBBBB
    XXXXXX
    XXXXXX
    BBBBBBBB
    BBBBB BBBBBBBBBB

    BBBBBBBB
XXXXXXX
XXXXXXX
