# Generated by Django 4.2.4 on 2023-09-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0002_alter_quiz_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="required_score_to_pass",
            field=models.IntegerField(help_text="required score in %"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="time",
            field=models.IntegerField(help_text="Time in Minutes"),
        ),
    ]
