# Generated by Django 3.2 on 2023-09-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_alter_quiz_required_score_to_pass_alter_quiz_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
