# Generated by Django 3.2 on 2023-09-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0006_quiz_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['difficulty'], 'verbose_name_plural': 'Quizes'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=7),
        ),
    ]
