# Generated by Django 3.2 on 2023-09-06 23:45

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0007_auto_20230906_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(difficulty='easy', then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(difficulty='medium', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(difficulty='hard', then=django.db.models.expressions.Value(3)), default=django.db.models.expressions.Value(4), output_field=models.IntegerField())], 'verbose_name_plural': 'Quizes'},
        ),
    ]
