# Generated by Django 3.2 on 2023-09-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0011_auto_20230908_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(verbose_name='Number of Questions'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(help_text='Required score, ex: 6, then (6=score/10=questions) to pass', verbose_name='Required score to pass'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(help_text='Time in Minutes', verbose_name='Time'),
        ),
    ]
