# Generated by Django 3.2 on 2023-08-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/cover/%Y/%m/%d/')),
            ],
        ),
    ]
