# Generated by Django 3.2 on 2023-08-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heranca', '0002_noticia_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_letter',
            fields=[
                ('letter', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dict_indigenous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=140)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heranca.dict_letter')),
            ],
        ),
    ]
