# Generated by Django 4.2.4 on 2023-09-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("heranca", "0005_alter_dict_letter_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Dict_indigenous",
            new_name="Dict_indigenou",
        ),
        migrations.RenameModel(
            old_name="Noticia",
            new_name="New",
        ),
    ]
