# Generated by Django 3.2 on 2023-09-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heranca', '0006_rename_dict_indigenous_dict_indigenou_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict_indigenou',
            name='alphabetical_order',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dict_letter',
            name='alphabetical_order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
