# Generated by Django 3.2 on 2023-09-04 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heranca', '0007_auto_20230903_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dict_letter',
            options={'ordering': ['letter_char']},
        ),
    ]
