# Generated by Django 3.2 on 2023-09-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heranca', '0008_alter_dict_letter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dict_indigenou',
            options={'ordering': ['name']},
        ),
    ]
