# Generated by Django 3.2 on 2023-09-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heranca', '0009_alter_dict_indigenou_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='conteudo_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='new',
            name='conteudo_pt_br',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='new',
            name='titulo_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='new',
            name='titulo_pt_br',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='dict_indigenou',
            name='alphabetical_order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Alphabetical Order'),
        ),
        migrations.AlterField(
            model_name='dict_indigenou',
            name='description',
            field=models.CharField(max_length=140, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dict_indigenou',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='new',
            name='conteudo',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='new',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
