# Generated by Django 3.2 on 2023-09-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heranca', '0010_auto_20230908_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict_letter',
            name='alphabetical_order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Alphabetical Order'),
        ),
        migrations.AlterField(
            model_name='dict_letter',
            name='letter_char',
            field=models.CharField(max_length=1, verbose_name='Letter Char'),
        ),
    ]
