# Generated by Django 3.2 on 2023-09-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heranca', '0011_auto_20230908_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='conteudo',
            field=models.TextField(verbose_name='Conteudo'),
        ),
        migrations.AlterField(
            model_name='new',
            name='conteudo_en',
            field=models.TextField(null=True, verbose_name='Conteudo'),
        ),
        migrations.AlterField(
            model_name='new',
            name='conteudo_pt_br',
            field=models.TextField(null=True, verbose_name='Conteudo'),
        ),
    ]
