# Generated by Django 3.2 on 2023-09-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heranca', '0016_post_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict_indigenou',
            name='description',
            field=models.CharField(max_length=640, verbose_name='Description'),
        ),
    ]
