# Generated by Django 3.2 on 2023-09-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heranca', '0017_alter_dict_indigenou_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict_indigenou',
            name='description',
            field=models.CharField(max_length=740, verbose_name='Description'),
        ),
    ]
