# Generated by Django 3.2 on 2023-10-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heranca', '0018_alter_dict_indigenou_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='conteudo',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='new',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
