# Generated by Django 3.2 on 2023-10-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heranca', '0019_auto_20231005_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='title_en',
            field=models.CharField(max_length=220, verbose_name='Conteudo'),
        ),
    ]
