# Generated by Django 3.2 on 2023-10-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heranca', '0020_alter_new_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='title_en',
            field=models.CharField(max_length=220, verbose_name='Title - (Titulo Ingles)'),
        ),
    ]
