BBBB BBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
       BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXX XXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'Tribo Próximas') XXXXX
                        XXXXXX
                    XXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Saiba onde encontrar tribos próximas a você para visitá-las.') XXXXX
                        XX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Cadastre-se para sabe mais') XXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXX XXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXX
                        XXXXXX
                    XXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXX XXXXXXXXX XXXXXX XXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXX XXXX XXXX XXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXX XXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXX
                        XXXXXX
                    XXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXX XXXXXXXXX XXXXXX XXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXX XXXX XXXX XXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXX XXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXX
                        XXXXXX
                    XXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXX XXXXXXXXX XXXXXX XXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXX XXXX XXXX XXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXX
            XXXX gettext(u'Notícias') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX      
                    BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                    BBBBBB 
                XXXXXX   
               
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                
                BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBB
                XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBXXXXXXXBBBBB XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBBBBB
            XXXXXX
        XXXXXXXXXX      
        XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXX XXX X XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXX
                    XXXXX BB BBBBBBBBBBBBBB BB BXXXXBBBBXXXXXBBBBBX
                    XXXXXX XX
                    XXXXXXX XXX
                    XXXXXXXXXXX X
                        XX X
                            XXXXXX X
                        XX
                        XXXX X
                            XXXXXX X
                        X
                    X
                XXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX
            
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX
            
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                    XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX X XX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX
            XXX
        XXXXXXXXX        
    XXXXXXX
    XXXXXXXX XXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXX
             gettext(u'Mais Notícias') 
        XXXX
        XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'”Enquanto existir uma erva, uma árvore ou um rio no planeta, nós povos indígenas existiremos.” ') XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXX XXXXXX XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX gettext(u'Neste quiz, convidamos você a embarcar em uma jornada fascinante pela ') XXX gettext(u'herança cultural de tribos indígenas.') XXXX  gettext(u'Explore conosco ') XXX gettext(u'a riqueza das tradições, histórias e costumes') XXXX XX XXXXX XXXX XXXXXXXX XXXXX XXXXXXXXXXX XX XXXXX XXX XXXXXXXX
                        XXXXXX XXXX XX XXXXXXXXX X XXXXXXXXX X XXXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX XX
                    XXXX
                    XX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Cadastre-se para sabe mais') XXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXX XXXXX XXXXXX XXXXX XXXXXXXXXX XXXX X XXXXXXXX XX XXX XXXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXX XX XXXXXX XXXXXXXXXX XXXXXXX XXXXXXX X XXXXXXX XXX XXXXXXXXXX XXXXXXXXX X XXXXXXXX XXX XXXXXXXX XXXXX XXXXXXXXXXX XX XXXXX XXX XXXXXXXX
                        XXXXXX XXXX XX XXXXXXXXX X XXXXXXXXX X XXXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX XX
                    XXXX
                    XX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Cadastre-se para sabe mais') XXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'POLÍTICA DE PRIVACIDADE') XXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'TERMOS DE USO') XXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'CENTRAL DE AJUDA') XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXX   
XXXXXXX
XXXXXXX