BBBB BBBBBB
BBBB BBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX
    XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXX
            BB BBBBB BB BBBBBBBBBBBBXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBXXXXXXXXXXXXXXXXX
            BBBBXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  XXXXXXBBB BBBBBBBBBBBBBB BBBBXXXXXXXXXXXXXXXXX
            BBBBB
            
            BB BBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
            BBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB
        XXXXX
    XXXXXX
XXXXXXXXX