BBBB BBBBBB
BBBB BBBB

BB BBBB BB BBBB
XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB
        BBBB gettext(u'Digite a palavra') 
        BBBBBX      
        XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX
        XXXXXXXXX
    XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'INÍCIO') XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'DICIONARIO') XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'COMUNIDADE') XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  XXXXXXBBB BBBBBBBBBBBBBBBBBBXX gettext(u'QUIZ') XXXXXXXXX
            BB BBBBB BB BBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBXX gettext(u'PT-BR') XXXXXXXXX
            BBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  XXXXXXBBB BBBBBBBBBBBBBB BBBBXX gettext(u'EN-US') XXXXXXXXX
            BBBBB
            
            BB BBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXX gettext(u'SAIR') XXXXXXXXX
            BBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX gettext(u'ENTRAR') XXXXXXXXX
            BBBBB
        XXXXX
    XXXXXX
XXXXXXXXX
BBBB BBBB BB BBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX  XXXXXXXXXXXXXXXXXX
            XXXXX
                XXXXXXX
            XXXXXX
        XXXX
    XXXXXXXXX
BBBBB

