BBBB BBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXX  gettext(u'Perfil') XXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Sair') XXXX
    BBBB
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXX gettext(u'Entrar') XXXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Registrar') XXXX
        
    BBBBB
    XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        BB BBBBB BB BBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBXXXXXXXXXXXXXXX
        BBBB
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  XXXXXXBBB BBBBBBBBBBBBBB BBBBXXXXXXXXXXXXX
        BBBBB
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Quem somos') XXXX
    XXXXXX
XXXXXX
    
    
    