BBBB BBBBBB
BBBB BBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBB
            XXXX XXXXXX XXXXXXX
            BBBB
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
            BBBBB
        XXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXXFFFFFXXXXX
        BBBB
        XXX XXXXXXXXXXXXXXXXXX gettext(u'Usuário não cadastrado!') XXXXX
        BBBBB
        
    XXXXXX
    XXXX gettext(u'Perfil') XXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXX  gettext(u'Perfil') XXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Sair') XXXX
    BBBB
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXX gettext(u'Entrar') XXXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Registrar') XXXX
        
    BBBBB
    XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        BB BBBBB BB BBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBXXXXXXXXXXXXXXX
        BBBB
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  XXXXXXBBB BBBBBBBBBBBBBB BBBBXXXXXXXXXXXXX
        BBBBB
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Dicionario') XXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Comunidade') XXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXX
    XXXXXX
XXXXXX
    
    
    