XXXX XXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXX
		XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXX
			XXXXXX XXX XXX XXXXXXXXXXX
			XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
				BBBBBBBBBB
				
				XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXX
		XXXXXX
		
		XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXX
			BB BBBBBBBBBBBBB XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
			XXXXXXXXX XXX XXX XXX XXXXXXXXXXX
			XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBXX
				BBBBBBBBBB
				
				XXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX   
				XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXX
		XXXXXX
	XXXXXX
XXXXXX