BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBB
BBBBBBBB BBBBBBBBBBBB
BBBBB BBBBBBBBBBBBB BBBBB
BBBBB BBBBBBB
XXXXXX
    XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX      
                XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXX XX XXXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX   
        XXXXXX
    XXXXXXXXXX
    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXX XXX X XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXX X XX
            
            XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXX
                XXXXX XXXXX
                XXXXXXXXX XXXXX
                XXXXXXXXXXXXXXXX XXXXXX 
                XXXXXX XX
                XXXXXXX XXX
                XXXXXXXXXXX X
                    XX X
                        XXXXXX X
                    XX
                    XXXX X
                        XXXXXX X
                    X
                X
            XXX


            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
                XXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XX
            XXX
        
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXXXXXXXXXXX X XXXXXXXXXXXXX X XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXXXXXXXXXXX X XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX X XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXX
            XXX
        
            XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            X
        XXX
        XXXXXXXXX        
XXXXXXX
BBBBBBBB BBBBBBB