BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
XXXXXX  
    BBBBB BBBBB
        
    BBBBBBBB BBBBB
XXXXXXX
XXXXXX
    BBBBB BBBBBBB
    XXXXX XXXXXXXXXXXXXXXXXXX
       
        BB BBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXX XXXXX
                        XXXXXX
                    XXXXXX
                BBBBBB
            XXXXXX
        BBBB
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX  
            XXXX XXXXXXXXXXXXXXXXXX
                BBB BBBBBB BB BBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXX XXXXX
                        XXXXXX
                    XXXXXX
                    BBBBBB
                XXXX
                BBBBBB
    
                BBB BBBBBB BB BBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXX XXXXX
                        XXXXXX
                    XXXXXX
                    BBBBBB
                XXXX
                BBBBBB
            XXXXXX  
        BBBBB
    XXXXXXX
    BB BBBBBBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    BBBB
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
    BBBBB
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
            XXXXXX
    XXXXXXXXXX
    
    
    BB BBBBBBBBBBBBB   
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXX XXXXX X XXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBB  BBBBBBBBBBBBBBBBXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        BBB BBBBBBBBBB BB BBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXX XXXXX
                            XXXXXX
                        XXXXXX
                        BBBBBB
                    XXXX
            
                BBBBBB
            XXXXXX
        XXXXXXXXXX   
    BBBBB
    BBBBBBBB BBBBBBB
XXXXXXX
