BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX    
    BBBBB BBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBXX
    BBBBB BBBBBBBBBBBBBBBBB
    BBBBBBBB BBBBBBBBBBBBBBBBB
    BBBBBBBB BBBBBBBBBBBB
    XXXXXXXBBBBB BBBBBBBBBBBBB BBBBBXXXXXXXX

XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXX
        BBBBB BBBBBBB
        
        
        BBBBBBBB BBBBBBB
    XXXXXX
    BBBBB BBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        BBBBB BBBBBBB
        BBBBBBBB BBBBBBB
    BBBBBBBB BBBBBBBBBBBB

XXXXXXX
XXXXXXX


