BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB

BBBBBBBB BBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Quiz - Tribos Indígenas') XXXXX
    XXXXXX

    XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXXXX
    XXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    BBB BBBB BB BBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBB B B
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX 
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBBBBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBB BB BBBB
                        XX
                        BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXXX
                        BBBBB
                        XXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXX
                        XXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX
                        XXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        X
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBB BB BBBBXBBBBBBBBBX
                        XXXXXX
                        FFFFF X XXXXX FFFFF
                        XXXX XXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBB BB BBBB
                                 gettext(u'JOGAR!') 
                            BBBB
                                 gettext(u'JOGAR DE NOVO!') 
                            BBBBB
                        XXXXXX
                    XXXX
                    BBBBB
                BBBBBB    
            XXXXXX
        BBBBB
    BBBBBB          
    XXXXXXXXXX
XXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
    XXXXXX
XXXXXXXXXX
BBBBB BBBBBBB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
BBBBBBBB BBBBBBB
BBBBBBBB BBBBBBB

