BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBB

BBBBBBBB BBBBB

BBBBB BBBB

BBBBBBBB BBBB

BBBBB BBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXX X FFFFFFX
        XXX XXXXXXXXXXXXXXX X XX

        XXXXXXXX XXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
            XX XXXXXX XXX XXXXXXXXX X XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            XX XXXXXX XXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X

            XX XXXXXX XXX XXXXXXXXX X XX X
                XXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXX
            X
        X

        XXXXXXXX XXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXX X XXXXXXXXX X XX X
                XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX XX XXXXXXXXXXXXXXXX XXX XXXXXXXXX X XX X
                XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXX X
                    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXX
                X
            X
        X

        XXXXXXXX XXXXXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXX X XX X
                XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        X

        XXXXXXXX XXXXXXXXXXXX X
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXX
            X
        X
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXX
            XX XXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
XXXXXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXX

    XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXX
BB BBBBBB BB BBB BBBB
    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXX XXXXXXXXXXXXXX
            BBB BBBBBBBBBB BB BBBB
                XXXX XXXXXXXXXXXXXXXXX
                    BBB BBBBBBBBB BBBBBBB BB BBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                            XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX
                            BBB BBBBBB BB BBBBBBB
                                XXXX XXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX X X XXXXXXX XXXXXXXXX
                                    XXXXXX XXXXX X XXXXXXXXXX
                                XXXXXX
                            BBBBBB                          
                        XXXXXX
                    BBBBBB
                XXXXXX
            BBBBBB
        XXXXXX
        XXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX


    XXXXXXX
    XXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
BBBB
    XXXX XXXXXXXXXXXXXXX
        BB BBBBBB
            XXXXXXXXXXXX XXXX XXXXXXX  XX XXXXX
        BBBB
            XXXXXXXXX XXX XXXXXXXXX XXX X XXXX XXXXXXXXX XXXXXXX XXXX XXXXX XXXXX
        BBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX
        BBB BBB BB BBBBBBB
            XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX
                BB BBBBBBBBBBBB BB BBBBXXXXXXXXX
                BBBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBXXXXXXXXXX
                BBBBXXXXXXXXX
                BBBBBXX
                
                BB BBBB BB BBBB BBBBBBBBBB
                X XXX XXXXXXXXXXX
                BBBB
                    BB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXX XXXXXXXXX 
                    BBBB
                        XXXXXX
                        XXXXXXXX XXXXXXXX 
                        XXX XXXXXXXXX 
                    BBBBB
                BBBBB
            XXXXXX
        BBBBBB
    XXXXXX
XXXX
XXXX
BBBBB


XXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB BBBBBBB